workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
    variables:
      XCODE_PROJECT_PATH: TDS-Carplay.xcodeproj
    scripts:
      - xcode-project
    artifacts:
      - build/ios/ipa/*.ipa
