workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - xcode-project build-ipa --project "TDS Video.xcodeproj" --export-options-plist exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
