workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - xcode-project build-ipa --project TDS-Carplay.xcodeproj
    artifacts:
      - build/ios/ipa/*.ipa
