workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - xcode-project build:
          project_path: TDS-Carplay.xcodeproj
    artifacts:
      - build/ios/ipa/*.ipa
